version: '3.9'

services:

  db:
    image: postgres:latest
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./todo_notes
    ports:
      - 8080:8080
    command: bash -c "
      python manage.py migrate
      && python manage.py addusers
      && python manage.py addtodo
      && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy
  